
# preload = ["./preload.ts"]
jsx = "react"
jsxFactory = "h"
jsxFragment = "Fragment"
jsxImportSource = "react"
smol = true
# logLevel = "debug" # "debug" | "warn" | "error"

[define]
# "process.env.NODE_ENV" = "'development'"

[loader]
# ".bagel" = "tsx"

# telemetry = false

[install]
optional = true
dev = true
peer = true
production = false
exact = false
saveTextLockfile = true
auto = "auto"
frozenLockfile = false
dryRun = false
# globalDir = "~/.bun/install/global"
# globalBinDir = "~/.bun/bin"
# registry = "https://registry.npmjs.org"

[install.scopes]
# myorg = "https://username:password@registry.myorg.com/"

# ca = "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----"
# cafile = "path/to/cafile"

[install.cache]
# dir = "~/.bun/install/cache"
disable = false
disableManifest = false

[install.lockfile]
save = true

[run]
shell = "bun"
bun = true
silent = true
